dist: trusty
sudo: false

language: node_js
node_js:
  - "10"


   
cache:
  directories:
     - ./node_modules

before_install:
  - sudo -E apt-get -yq --no-install-suggests --no-install-recommends --allow-unauthenticated $(travis_apt_get_options) install google-chrome-stable 
  
install:
  - npm test

script:
  - npm run test -- --no-watch --no-progress --browsers=ChromeHeadlessCI
  - npm run e2e -- --protractor-config=e2e/protractor-ci.conf.js
